server:
  port: 8010
spring:
  application:
    name: order
  datasource:
    name: scloud
    url: jdbc:mysql://localhost:3306/scloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.yang.entity
