server:
  port: 8761
#注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #表示是否将自己注册到Eureka Server
    register-with-eureka: false
    #表示是否从其它注册中心获取注册的服务信息
    fetch-registry: false

